media_entity_podtoo.settings:
  type: config_entity
  mapping:
    color:
      type: string
      label: 'Background color'
    display:
      type: string
      label: 'Player display'
    username:
      type: boolean
      label: 'Username'
    email:
      type: boolean
      label: 'Email'
    uid:
      type: boolean
      label: 'uid'
